export default [
  {
    id: 1,
    title: "Phang Nga Bay",
    location: "Phuket",
    googleMapsUrl: "https://goo.gl/maps/wNfHQSJwQCHZVh1s5",
    startDate: "08 Feb, 2018",
    endDate: "10 Feb, 2018",
    description:
      "Phang Nga Bay lies between southern Thailand's mainland and Phuket Island. Also known as Ao Phang Nga National Park, it's characterized by limestone cliffs and rock formations, as well as mangrove forests and small islands. Among the islands are Koh Tapu, known as James Bond Island for its appearance in a Bond film. Koh Phanak Island is known for its caves and lagoons. The bay's waters are dotted with coral reefs. ",
    imageUrl: "phuket.jpg",
    alt: "Phang Nga Bay at sunset",
  },
  {
    id: 2,
    title: "Cayo Coco",
    location: "Cuba",
    googleMapsUrl: "https://goo.gl/maps/UvVvWFm3rykD2oav9",
    startDate: "09 Nov, 2018",
    endDate: "15 Nov, 2018",
    description:
      "Cayo Coco is a tropical island in the Jardines del Rey chain, off central Cuba. Known for its white-sand beaches and coral reefs, its northern coast is dotted with all-inclusive resorts. Natural features include lagoons and marshes that are home to birds such as the white ibis as well as a native colony of pink flamingos that's ranked among the largest in the Americas. ",
    imageUrl: "cuba.jpg",
    alt: "Beach in Cayo Coco",
  },
  {
    id: 3,
    title: "Mount Royal",
    location: "Montreal",
    googleMapsUrl: "https://goo.gl/maps/QwaiGW3NgPJLwFfM8",
    startDate: "17 Feb, 2019",
    endDate: "18 Feb, 2019",
    description:
      "Mount Royal is a large intrusive rock hill or small mountain in the city of Montreal, immediately west of Downtown Montreal, Quebec, Canada. The best-known hypothesis for the origin of the name Montreal is that the hill is the namesake for the city.",
    imageUrl: "montreal.jpg",
    alt: "View from top of Mount Royal",
  },
  {
    id: 4,
    title: "Victoria Peak",
    location: "Hong Kong",
    googleMapsUrl: "https://goo.gl/maps/KZHLHy5F2xGxgcMw7",
    startDate: "10 Mar, 2019",
    endDate: "12 Mar, 2019",
    description:
      "Victoria Peak is a hill on the western half of Hong Kong Island. It is also known as Mount Austin, and locally as The Peak only generally. With an elevation of 552 metres, it is the tallest hill on Hong Kong Island, and the 29th tallest in the territory of Hong Kong.",
    imageUrl: "hongkong.jpg",
    alt: "View from top of Victoria Peak",
  },
  {
    id: 5,
    title: "Ruins of St. Paul's",
    location: "Macau",
    googleMapsUrl: "https://goo.gl/maps/TeWVpkGWXHpp8cxJ6",
    startDate: "20 Mar, 2019",
    endDate: "21 Mar, 2019",
    description:
      "The Ruins of Saint Paul's are the ruins of a 17th-century Catholic religious complex in Santo António, Macau, China. They include what was originally St. Paul's College and the Church of St. Paul also known as Mater Dei, a 17th-century Portuguese church dedicated to Saint Paul the Apostle.",
    imageUrl: "macau.jpg",
    alt: "Front of Ruins of St. Paul's",
  },
  {
    id: 6,
    title: "Walt Disney World",
    location: "Orlando",
    googleMapsUrl: "https://goo.gl/maps/c4G53tF7XC6J2ygz8",
    startDate: "04 Sept, 2022",
    endDate: "11 Sept, 2022",
    description:
      "The Walt Disney World Resort, also called Walt Disney World or Disney World, is an entertainment resort complex in Bay Lake and Lake Buena Vista, Florida, United States, near the cities of Orlando and Kissimmee.",
    imageUrl: "disneyworld.jpg",
    alt: "Fireworks at Walt Disney World Magic Kingdom",
  },
  {
    id: 7,
    title: "The Round Tower",
    location: "Copenhagen",
    googleMapsUrl: "https://goo.gl/maps/3hZ9gp5CVGgpV7Ag7",
    startDate: "05 Dec, 2022",
    endDate: "06 Dec, 2022",
    description:
      "The Round Tower is a 17th-century tower in Copenhagen, Denmark, one of the many architectural projects of Christian IV of Denmark. Built as an astronomical observatory, it is noted for its equestrian staircase, a 7.5-turn helical corridor leading to the platform at the top, and its views over Copenhagen.",
    imageUrl: "copenhagen.jpg",
    alt: "Inside of The Round Tower",
  },
  {
    id: 8,
    title: "Nyhavn",
    location: "Copenhagen",
    googleMapsUrl: "https://goo.gl/maps/bo2MyX3qRni4ZoWm7",
    startDate: "07 Dec, 2022",
    endDate: "08 Dec, 2022",
    description:
      "Nyhavn is a 17th-century waterfront, canal and entertainment district in Copenhagen, Denmark. Stretching from Kongens Nytorv to the harbour front just south of the Royal Playhouse, it is lined by brightly coloured 17th and early 18th century townhouses and bars, cafes and restaurants.",
    imageUrl: "nyhavn.jpg",
    alt: "Street view of Nyhavn",
  },
  {
    id: 9,
    title: "La Sagrada Familia",
    location: "Barcelona",
    googleMapsUrl: "https://goo.gl/maps/XCREzhTmFdVWT3sz5",
    startDate: "30 Apr, 2023",
    endDate: "01 May, 2023",
    description:
      "The Basílica i Temple Expiatori de la Sagrada Família, shortened as the Sagrada Família, is an unfinished church in the Eixample district of Barcelona, Catalonia, Spain. It is the largest unfinished Catholic church in the world.",
    imageUrl: "barcelona.jpg",
    alt: "white concrete building near trees in daytime",
  },
];
